### ISSUE TITLE
Line break and indentation after `pre`

### ISSUE THREAD

**Issue by larsrh** [propensive/rapture#105]
The following will look wrong in a browser, because the first line of the `pre` is indented, as opposed to the second and subsequent lines.

``` scala
scala> import rapture.html.htmlSyntax._
import rapture.html.htmlSyntax._

scala> Html(Head, Body(Div(Pre("abc\ndef")))).format
res0: String =
<html>
  <head/>
  <body>
    <div>
      <pre>
        abc
def
      </pre>
    </div>
  </body>
</html>

```

**Comment by propensive** [comment]
It looks like I need to completely stop any extra whitespace being added for `pre` tags...
