### ISSUE TITLE
JSON backends latest version is still M3 although M4 was released.

### ISSUE THREAD

**Issue by sscarduzio** [propensive/rapture#109]
<img width="677" alt="screenshot 2016-02-20 11 19 09" src="https://cloud.githubusercontent.com/assets/1327189/13196388/de9fefb4-d7c3-11e5-9389-a10b2619fbe8.png">

**Comment by propensive** [comment]
Thanks @sscarduzio—I think you've found this is working on the M5 release now!

**Comment by sscarduzio** [comment]
Yes sir, looks very different now :+1: 
<img width="685" alt="screenshot 2016-02-25 13 43 03" src="https://cloud.githubusercontent.com/assets/1327189/13321241/c39fda5c-dbc5-11e5-89e1-1b4d31cdcbc5.png">
