### ISSUE TITLE
Rapture website suggests using an old version

### ISSUE THREAD

**Issue by sscarduzio** [propensive/rapture#110]
<img width="462" alt="screenshot 2016-02-20 11 22 56" src="https://cloud.githubusercontent.com/assets/1327189/13196417/6876b70e-d7c4-11e5-8964-fa617d38d3fe.png">

**Comment by propensive** [comment]
Hopefully we'll jump straight to `M5` this weekend.

**Comment by mnd999** [comment]
I guess this is kinda fixed. The website is gone completely.

**Comment by propensive** [comment]
Yes... it failed on its own, somehow, but I'm planning to stop maintaining Rapture, and pull the best parts out into new projects.
