### ISSUE TITLE
Mismatched operators and types

### ISSUE THREAD

**Issue by ShaneDelmore** [propensive/rapture#129]
fr"Bonjour" & en"Hello"
res: I18n[String, Fr with En] = fr|en:"Hello"

I would expect the result to be fr & en to be the resulting type not fr | en

**Comment by mrmiywj** [comment]
Look through the source code, I don't think that '|' means or ..
It's just a symbol

**Comment by ShaneDelmore** [comment]
I didn't mean to imply I thought it meant OR, just that it is a different symbol than used when creating the data which could be confusing.  They used to line up and now they don't.  If this isn't something we want to line up then feel free to close the ticket.

**Comment by mrmiywj** [comment]
Yep, I will try a PR

**Comment by ShaneDelmore** [comment]
I'll keep an eye on this and if you merge in changes I will update the docs to reflect it.

**Comment by propensive** [comment]
Thanks!
