### ISSUE TITLE
Update Circe to 0.4.1

### ISSUE THREAD

**Issue by sscarduzio** [propensive/rapture#187]
We have a compatibility [issue](https://github.com/typelevel/cats/issues/1037) between the current Cats (0.5.0) and the latest rapture-json-circe 2.0.0-M5.

It would be great if rapture-json-circe could depend on Circe 0.4.1, so people's projects could have one less dependency (cats would come with Circe) and - above all - no Cats version conflicts.

https://cdn.meme.am/instances/55052636.jpg

(pic related)

**Comment by sscarduzio** [comment]
Oh, I just saw this is fixed in master! Can we have a new M\* release?

**Comment by propensive** [comment]
Do you mind using a snapshot release for the next couple of days?

```
resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "com.propensive" %% "rapture" % "v2.0.0-M5-99-g5773008-SNAPSHOT"
```

**Comment by sscarduzio** [comment]
NP, glad to. Thanks.
