### ISSUE TITLE
Add missing HTTP methods (options, delete, trace, head)

### ISSUE THREAD

**Issue by emanresusername** [propensive/rapture#202]
all the other ones are [here](https://github.com/propensive/rapture/blob/dev/net/shared/src/main/scala/rapture/net/http.scala#L31-L81) wondering if it's easy to add httpDelete, or if that's already handled somewhere else?

**Comment by propensive** [comment]
Hi @emanresusername,

It's probably not too difficult. Looks like we also need:
- OPTIONS
- DELETE
- TRACE
- HEAD

I'll mark this as "easy" in case anyone else wants to have a go, if not, I'll probably pick it up soon.

**Comment by mielientiev** [comment]
@propensive I think I can take it

**Comment by mielientiev** [comment]
Delete, options, and trace methods were added. 
Need to add bunch of unit tests for it #204 :)
