### ISSUE TITLE
Parsing problem on classes with defaults

### ISSUE THREAD

**Issue by johannegger** [propensive/rapture#207]
the following code shows the problem:

```
import rapture.json._
import jsonBackends.circe._
import formatters.compact._

case class Foo(bar1:Foo.Bar=Foo.Bar(), bar2:Foo.Bar=Foo.Bar())
object Foo{
  case class Bar(param1:Option[String]=None, param2:Option[Long]=None)
}

val myFoo = Foo(Foo.Bar(param2 = Some(42)))
val str = Json.format(Json(myFoo))
val parsedFoo = Json.parse(str).as[Foo]

assert( parsedFoo == myFoo)
```

the problem is that `parsedFoo` evaluates to `Foo(Bar(None,None),Bar(None,None))`  
btw the problem exists on the jawn-backend as well

as a workaround i removed the defaults in Foo - then everything works

**Comment by propensive** [comment]
Thanks for the bug report! I'll have a look into what's going wrong...

**Comment by mielientiev** [comment]
@propensive I assume the problem at `rapture.data.Macros.extractorMacro`. I've spent some time for debugging it, but I still don't get how it works, and why it generates a bunch of nested `asInstanceOf` blocks :)

**Comment by propensive** [comment]
Yeah, it's a mess, and quite scary... It was written before quasiquotes, which makes it that much harder to understand. I think ultimately it needs rewriting... Thanks for looking, though!

**Comment by propensive** [comment]
Fixed!
