### ISSUE TITLE
Sources jar are not eclipse friendly

### ISSUE THREAD

**Issue by fanf** [propensive/rapture#24]
The provided sources jars are making Eclipse^WScalaIDE sad: it is not able to find the source file for the classes. 

The problem is that Eclipse is dumb. I mean, it doesn't even try.
For example far class rapture.net.HttpUrl.class in rapture-net, Eclupse will look in the jar, in directory ./rapture/net. Of course, as there is no such directory (because the source files are directly in root directory), Eclipse is lost and display the byte code with a nive "I'm lost" message. 
Unzipping the jar, creating rapture/net, moving source into it, creating a new jar, telling eclipse to use that jar makes Eclipse happy. And afterward, I'm able to see source in eclipse.  

It would be great if you could make Eclipse less dumb. 
If the task is overwhelming, or you simply want to work in less horrible things, could you add the package directory in source jar so that Eclipse is able to find its way ?

**Comment by propensive** [comment]
I'm going to create the package structures inside the source directories, and update the `src` symlinks to point inside them. This seems like the simplest solution, and I can get this into Wednesday's release, I hope!
