### ISSUE TITLE
Json number modified after parse(using lift as backend)

### ISSUE THREAD

**Issue by noru** [propensive/rapture#26]
```
import rapture.json.jsonBackends.lift._
val json = Json.parse("""{"num": 3524229266820255333}""")
val WTF = json.num // !!! 3524229266820255200
```

If using jawn, the problem went away.

UPDATE: using jawn still has same problem, seems in json buffer it is DoubleNum is used instead of Long.

**Comment by propensive** [comment]
I think in Lift, numbers are represented by `Double`s, so you see the rounded version. Jawn represents numbers as `String`s until you've decided what type you want to create, so you can use a `BigDecimal`s to represent long numbers.

You'll always need a `BigDecimal` to represent that many digits, and if you use `num.as[BigDecimal]` in Jawn, you'll get the right number. If you do the same in Lift, you'll get a `BigDecimal` created from a `Double` of that number (which is rounded).

As long as Lift doesn't support anything other than `Double`s (and that might have changed since I last checked...) there's not a lot we can do about this, other than use a different backend.

**Comment by noru** [comment]
Thanks for your timely explanation! However, after multiple futile tries, I'm still pretty lost. Let me try to describe my tests as clear as possible.

 *1. using play as backend

``` scala
    import rapture.json.jsonBackends.play._
    val json = JsonBuffer.parse("""{"a": 3524229266820255334}""")

    json.b = ForcedConversion(LongNum(3524229266820255334L), nothing = false) // match error
    json.b = Some(3524229266820255334L)  // rounded in MutableCell
    json.b = 3524229266820255334L  // rounded
    json.b = "3524229266820255334" // string, not number
    val c = json.b.as[BigInt] // error, type mismatch: Expected number but found object

    Ok(json.toString())  // both 'a' and 'b' are formatted as 'undefined'
```

 *2. using jawn. Seems the problem only occurs when using JsonBuffer to assign a property

``` scala
    import rapture.json.jsonBackends.jawn._
    val json = JsonBuffer.parse("""{"a": 3524229266820255334}""")

    json.b = ForcedConversion(LongNum(3524229266820255334L), nothing = false) // ok in MutableCell, but formatted as undefined
    json.b = Some(3524229266820255334L)  // rounded in MutableCell
    json.b = 3524229266820255334L  // formatted as string
    json.b = "3524229266820255334" // formatted as string
    val c = json.b.as[BigInt] // error, type mismatch: Expected number but found object

    Ok(json.toString()) // json.a is always correctly formatted
```

**_Update:**_ Using Json.format(json) and ForceConversion will got proper formatted result.

 *3. using lift. According to your explanation, lift won't suit my case, just for reference 

``` scala
import rapture.json.jsonBackends.lift._
    val json = JsonBuffer.parse("""{"a": 3524229266820255334}""")

    json.b = ForcedConversion(LongNum(3524229266820255334L), nothing = false) // match error
    json.b = Some(3524229266820255334L)  // rounded in MutableCell, however the a is not
    json.b = 3524229266820255334L  // JString in MutableCell, formatted as rounded number
    json.b = "3524229266820255334" // JString in MutableCell, formatted as string
    val c = json.b.as[BigInt] // error, type mismatch: Expected number but found object

    Ok(json.toString())
```

Both BigInt/BigDecimal are tried and failed. 

My goal is pretty simple here: assign a Long to a json and have it properly formatted, no matter what backend to use. Is there anything else I can do? Really appreciated your help!

**_Update:**_ as my update in case 2, my problem seems have a workaround...

**Comment by mielientiev** [comment]
@propensive I'm not sure what happened, but

```
    import rapture.json.Json
    import rapture.json.jsonBackends.lift._
    val json = Json.parse("""{"num": 3524229266820255333}""")
    val WTF = json.num
```

returns `3524229266820255333` for M7 rapture version

**Comment by propensive** [comment]
I think I fixed it a while ago and forgot to close the ticket... ;)
