### ISSUE TITLE
the key String("xxx") is not in the dictionary

### ISSUE THREAD

**Issue by wiradikusuma** [propensive/rapture#273]
The following snippet **does not** show any error in IntelliJ:

	import rapture.json._
	import rapture.json.jsonBackends.jawn._

	val data = Json.parse(fromInputStream(req.getInputStream).mkString)

	if (data.foo.as[String] == "bar")
		data.entry.as[Vector[Json]].foreach { ... }

But when I run it from Gradle, it throws error:

	the key String("foo") is not in the dictionary
	the key String("entry") is not in the dictionary

What do I miss?

**Comment by tumakha** [comment]
The same exception with version "rapture_2.11" % "2.0.0-M9"

**Comment by winstonjr** [comment]
I was saying that the version is "rapture_2.12" "2.0.0-M9".
The version 2.0.0-M8 works properly. No error for this.

**Comment by mnd999** [comment]
You need some completely undocumented magic:

`import rapture.json.dictionaries.dynamic._`

**Comment by propensive** [comment]
Well done for finding that, @mnd999. Sorry it was thrown in there with so little explanation. Alternatively you can define an implicit "dictionary" of labels if you want to only allow a subset of strings to be usable as accessors for JSON values.

**Comment by propensive** [comment]
Note that I'm no longer maintaining Rapture, but I intend to pull some of the best parts out into new projects.
