### ISSUE TITLE
i18n underlying Map[ClassTag[_], T] misses languages when using refined types

### ISSUE THREAD

**Issue by joshlemer** [propensive/rapture#274]
```scala
import rapture.i18n._

import scala.util.Try

val greeting: I18n[String, En with Fr] = en"Hello" & fr"bonjour"

val biscuit: I18n[String, En with Fr] = I18n[En with Fr]("biscuit")

Try(greeting[En]) // Success(Hello)
Try(greeting[Fr])  // Success(bonjour)

Try(biscuit[En]) // Success(biscuit)
Try(biscuit[Fr]) // Failure(java.util.NoSuchElementException: key not found: rapture.i18n.Fr)
```
I believe this can be fixed if we move from ClassTags to Types, so that we can get the parents (in this case En, Fr) in the case that it is a refined type, or just get the type itself if not a refined type.

**Comment by propensive** [comment]
Thanks for reporting that, @joshlemer, and sorry it took me so long to respond. I think you're right, though I'm not sure I want to permit creation of values like this... If you feel like experimenting, I'd happily accept a PR, as I'm not doing much maintenance on `i18n` at the moment...

**Comment by joshlemer** [comment]
Hey @propensive , I actually did submit a PR for this ( #275 ), not sure if it is the direction you want the project to go in, but it is one possible solution :-)
