### ISSUE TITLE
Error: could not find implicit value for parameter ast: rapture.json.JsonBufferAst

### ISSUE THREAD

**Issue by akuznetsov-gridgain** [propensive/rapture#276]
Hi!

I'm trying to migrate from 2.11 v.1.1.0 to 2.12 v.2.0.0.M9.

and getting following exception:

> Error:(119, 38) could not find implicit value for parameter ast: rapture.json.JsonBufferAst
>     protected var prefs = JsonBuffer.empty

My code looks like:
   ```
 import rapture.json._
    import formatters.humanReadable._
    import jsonBackends.jackson._
   
    protected var prefs = JsonBuffer.empty
```
Any thoughts?

P.S. In 1.1.0 we used **import rapture.json.jsonBackends.scalaJson._**,
but I failed to find it in 2.0.0.M9, where it is now?

Thanks!

**Comment by propensive** [comment]
Hi, the standard library backend (`jsonBackends.scalaJson`) got removed because it was being removed from the standard library, and was very very slow. The Jackson backend does not support mutable JSON (it's the only one which doesn't), so if you change the dependency in the build to include one of the alternative backends (e.g. `rapture-json-spray` or `rapture-json-circe`), then you should be able to import that backend instead, and it should work.

**Comment by akuznetsov-gridgain** [comment]
Thanks!
I replaced jackson with circe and error dissapeared.
But now I got 100500 errors as:

> Error:(789, 9) the key String("filemanager") is not in the dictionary
>         prefs.filemanager.buffer.as[Int].getOrElse(DFLT_FILE_MANAGER_BUFFER)

Where  prefs is JsonBuffer and according to docs it shoud works (and it was in 1.1.0).

May be in 2.0.0.M9 I should import some "implict" magic?
Did not find any clue [here](https://github.com/propensive/rapture/blob/dev/doc/json.md#mutable-json).

Thanks!

P.S. What is better spray or circe? In case I'm using JSON to store app preferences?

**Comment by propensive** [comment]
That was some additional undocumented constraints which (and I'm completely culpable here, so sorry...) crept into the last release to try to add some safety around accessing values. There are two solutions, the easiest of which is to include,
```
import rapture.json.dictionaries.dynamic._
```

**Comment by propensive** [comment]
The alternative is to define,
```
implicit val dict = rapture.data.Dictionary.define("foo", "bar", "baz", ...)
```
where `foo`, `bar` and `baz` are all the labels you want to be able to access in JSON objects. It goes part of the way towards ensuring you don't write `bza` when you meant `baz`.

**Comment by akuznetsov-gridgain** [comment]
Thanks,

After I added "import rapture.json.dictionaries.dynamic._", my program compiled.

How about to update docs?

1. scalaJson - was removed.
2. jackson is readonly.
3. import rapture.json.dictionaries.dynamic._

**Comment by propensive** [comment]
Great! This would be good. Which docs were you using, by the way? I'm no longer actively maintaining Rapture, but I do plan to move the best bits into new projects where I can.

**Comment by akuznetsov-gridgain** [comment]
I used this one: https://github.com/propensive/rapture/blob/dev/doc/json.md

**Comment by propensive** [comment]
Ok, well that's under my control at least! Would you mind PRing the changes? Realistically, I won't have time, but I'll definitely merge changes if I get a PR. :)

**Comment by akuznetsov-gridgain** [comment]
I will prepare PR in a couple of days.

**Comment by propensive** [comment]
Thank you!

**Comment by akuznetsov-gridgain** [comment]
Prepared PR (from my own account):  https://github.com/propensive/rapture/pull/277
Please squash on merge.
