### ISSUE TITLE
[json-jackson] upgrade Jackson to 2.6.x

### ISSUE THREAD

**Issue by avdv** [propensive/rapture#29]
The Jackson 1.9 branch is in maintenance mode since a few years now. Maybe it's time to make a switch.

**Comment by propensive** [comment]
Yes, we should. Do you know how compatible the APIs are? My only experience of Jackson is having implemented the backend for Rapture...

**Comment by avdv** [comment]
Um, no. I haven't yet used Jackson myself.

But according to http://www.cowtowncoder.com/blog/archives/2012/04/entry_469.html it shouldn't be too hard.

So, I just gave it a spin; PR coming up...
