### ISSUE TITLE
Sonatype rejects `rapture-json-lift` during publishing

### ISSUE THREAD

**Issue by propensive** [propensive/rapture#48]
When publishing to Sonatype, including `json-lift` results in the artifact being consistently rejected, without any explanation.

**Comment by salvob41** [comment]
when import a dependency of rapture
`
<groupId>com.propensive</groupId>
<artifactId>rapture_2.11</artifactId>`

cannot build because of the error:

> Could not find artifact com.propensive:rapture-json-lift_2.11:jar:2.0.0-M3

a work around is put exclusions:

`
<dependency>
            <groupId>com.propensive</groupId>
            <artifactId>rapture_2.11</artifactId>
            <version>2.0.0-M3</version>
            <exclusions>
                <exclusion>
                    <groupId>com.propensive</groupId>
                    <artifactId>rapture-json-lift_2.11</artifactId>
                </exclusion>
            </exclusions>
        </dependency>`
