### ISSUE TITLE
Quick method for constructing new Json/Xml values

### ISSUE THREAD

**Issue by propensive** [propensive/rapture#71]
We would like to be able to easily construct new `Json` and `Xml` values from their raw representations, e.g.

```
val j: Json = Json.construct(raw)
```

Note that this should take an implicit `Ast`, whose `Representation` type should match the parameter type. See #70.

**Comment by chris-zen** [comment]
Actually _Json.construct_ expects two parameters, the _raw_ data, and a _path_. Could the path argument default to something ?

**Comment by propensive** [comment]
That's the current implementation, which always takes a `MutableCell`. I think the replacement should take a single parameter, which is the raw value. To use the current version, you should be able to put an empty `Vector()` in the second parameter.

**Comment by propensive** [comment]
I've just been looking into this, and discovered there is an `unapply` method which does almost what we want, though the usage is unconventional, and I'm wondering why I implemented it this way.

You can write the following,

```
val Json(x) = <value to be wrapped>
```

and the value `x` will be a new `Json` value, containing the `<value to be wrapped>`.

I'm going to leave the issue open for now, delay the milestone, and think about it some more.

**Comment by chris-zen** [comment]
Hi @propensive,
the current `unapply` breaks completely my intuition of what I would expect. Given the following code, I would expect `x` to be the raw value passed when constructing the Json (the `List(1,2,3)`)

```
val myJson = Json.construct(MutableCell(List(1,2,3)))
val Json(x) = myJson
x == List(1,2,3)  // true
```

This behaviour would also solve my problem with getting the raw value when using `.as[T]`, as my underlying raw value is an `Any` and the extractor `.as[Any]` fails for me with:

```
scala> json"""1""".as[Any]
<console>:18: error: ambiguous implicit values:
 both method jsonCastExtractor in object Json of type [T](implicit evidence$1: rapture.json.JsonCastExtractor[T], implicit ast: rapture.json.JsonAst)rapture.json.Extractor[T,rapture.json.JsonDataType[_, _ <: rapture.json.JsonAst]]
 and method anyExtractor in object Extractor of type [Data <: rapture.data.DataType[_, rapture.data.DataAst]]=> rapture.data.Extractor[Any,Data]{type Throws = Nothing}
 match expected type rapture.data.Extractor[Any,rapture.json.Json]
json"""1""".as[Any]
              ^
```

From my point of view it would be more intuitive to me to have something like:

```
Json.wrap(List(1,2,3))
Json.wrapMutable(List(1,2,3))
...
```

**Comment by propensive** [comment]
Yeah, I think you're right. The `unapply` intuition is backwards. I'm trying to work out why that implementation ever existed that way. Let's go with `Json.wrap`, and I'll include it in M4 next week.

**Comment by propensive** [comment]
I decided to call it `raw` in the end. Just waiting for PR #78 to test on CI.
