### ISSUE TITLE
Support full HTML syntax by migrating old code

### ISSUE THREAD

**Issue by srenault** [propensive/rapture#72]
Is there any reason why some attributes like `placeholder` are commented: https://github.com/propensive/rapture/blob/dev/html/shared/src/main/scala/syntax.scala#L453  ?

**Comment by propensive** [comment]
Support for HTML syntax is currently unfinished... The commented-out stuff is from an older version of the library, and you should be able to see the differences between each element there, and the code above.

Converting the remaining code would be a great contribution, incidentally!

I'm going to update this issue title to reflect that. :)

**Comment by srenault** [comment]
I'm ok to make a PR.

**Comment by propensive** [comment]
Awesome! Thanks!

Ask questions in the Gitter channel if you need any help. :)
