### ISSUE TITLE
JSON literals serialize all substitutions as if they're Strings

### ISSUE THREAD

**Issue by fatmalama** [propensive/rapture#73]
e.g.

```
scala> json"""{"a": 1}"""
res1: rapture.json.Json = {"a":1}

scala> val one = 1
one: Int = 1

scala> json"""{"a": $one}"""
res2: rapture.json.Json = {"a":"1"}
```

**Comment by propensive** [comment]
This is happening because generalized String serialization implicits are taking priority over the ones in Rapture JSON. I'll look to get a fix in the Feb 3 release.

**Comment by propensive** [comment]
This is now fixed, and will make it into the next release.
